# Generated by Django 4.2.1 on 2023-05-23 13:30

from django.db import migrations
import sanitizer.models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_auto_20211012_2105"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=sanitizer.models.SanitizedCharField(max_length=240),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=sanitizer.models.SanitizedTextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=sanitizer.models.SanitizedTextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=sanitizer.models.SanitizedCharField(max_length=240),
        ),
    ]
