# Generated by Django 4.2.1 on 2023-05-23 13:30

from django.db import migrations
import sanitizer.models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=sanitizer.models.SanitizedTextField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=sanitizer.models.SanitizedCharField(max_length=240),
        ),
    ]
